Map<String, String> en = {
  'Log In': 'Log In',
  'Sign Up': 'Sign Up',
  'I am a': 'I am a',
  'STUDENT': 'STUDENT',
  'TUTOR': 'TUTOR',
  'First name': 'First name',
  'Last name': 'Last name',
  'Email': 'Email',
  'Password': 'Password',
  'Country': 'Country',
  'City': 'City',
  'Send': 'Send',
  'OR\nSign Up with': 'OR\nSign Up with',
  'OR\nLog in with': 'OR\nLog in with',
  'Have an account?': 'Have an account?',
  'Email address or username': 'Email address or username',
  'Remember me': 'Remember me',
  'Forgot password?': 'Forgot password?',
  'Don’t have an account?': 'Don’t have an account?',
  'What’s Your Native Language?': 'What’s Your Native Language?',
  'This will help to find tutors who speak the same language as you.':
      'This will help to find tutors who speak the same language as you.',
  'Next': 'Next',
  'What Subjects Do You Want To Learn?': 'What Subjects Do You Want To Learn?',
  'You can add other subjects to your profile later.':
      'You can add other subjects to your profile later.',
  'Search courses': 'Search courses',
  'ADD NEW': 'ADD NEW',
  'Back': 'Back',
  'Add new time': 'Add new time',
  'to set your availability, choose in order the month then day of the month and then choose what  times is suitable for you':
      'to set your availability, choose in order the month then day of the month and then choose what  times is suitable for you',
  'Choose subject': 'Choose subject',
  'Name': 'Name',
  'Add': 'Add',
  'Forgot password': 'Forgot password',
  'Please enter your email or phone number then we will help you create a new password':
      'Please enter your email or phone number then we will help you create a new password',
  'Submit': 'Submit',
  'Profile': 'Profile',
  'Blog': 'Blog',
  'Title': 'Title',
  'Subtitle': 'Subtitle',
  'Subtitle here': 'Subtitle here',
  'title here': 'title here',
  'Article': 'Article',
  'Tags': 'Tags',
  '#design    #arabic': '#design    #arabic',
  '+ Add tag': '+ Add tag',
  'Cover image': 'Cover image',
  'Upload Cover Image': 'Upload Cover Image',
  'Draft': 'Draft',
  'Publish': 'Publish',
  'Community': 'Community',
  'body here': 'body here',
  'Subject': 'Subject',
  'Select': 'Select',
  'Category': 'Category',
  'Trending Topics': 'Trending Topics',
  'Trending Articles': 'Trending Articles',
  'Add Comment': 'Add Comment',
  'Comments': 'Comments',
  'Your rate:': 'Your rate:',
  'Write comment': 'Write comment',
  'Related Articles': 'Related Articles',
  'Featured Qs': 'Featured Qs',
  'Please fill all tags before adding': 'Please fill all tags before adding',
  'Edit': 'Edit',
  'Delete': 'Delete',
  'Add  new  article': 'Add  new  article',
  'Add  new  community': 'Add  new  community',
  'Calendar': 'Calendar',
  'Home': 'Home',
  'You should login or create new account to see your calender':
      'You should login or create new account to see your calender',
  'Today’s Class': 'Today’s Class',
  'Classes Schedule': 'Classes Schedule',
  'Monthly': 'Monthly',
  'Daily': 'Daily',
  "FAQ": "FAQ",
  'Queries you may have.': 'Queries you may have.',
  'My Favorites': 'My Favorites',
  'Popular Tutors': 'Popular Tutors',
  'see all': 'see all',
  'Find students': 'Find students',
  'Recent Requests': 'Recent Requests',
  'Tutors': 'Tutors',
  'Welcome': 'Welcome',
  'New\nClass !!': 'New\nClass !!',
  'Register now,\ndon\'t miss it': 'Register now,\ndon\'t miss it',
  'Upcoming Schedule': 'Upcoming Schedule',
  'Notifications': 'Notifications',
  'Messages': 'Messages',
  'Find Tutor': 'Find Tutor',
  'Find Student': 'Find Student',
  'Settings': 'Settings',
  'Customer Service': 'Customer Service',
  'Private': 'Private',
  'Group': 'Group',
  'From': 'From',
  'To': 'To',
  'Add start time first': 'Add start time first',
  'Add end time first': 'Add end time first',
  'Availability': 'Availability',
  'Set your availability first by choosing the month, then the day, and finally the time you are available.':
      'Set your availability first by choosing the month, then the day, and finally the time you are available.',
  'Select date': 'Select date',
  'Times': 'Times',
  'Certificates': 'Certificates',
  'Issued by': 'Issued by',
  'Issued Date': 'Issued Date',
  'download': 'download',
  'Add a certification': 'Add  certification',
  'choose': 'choose',
  'Cancel': 'Cancel',
  'Save': 'Save',
  "Re-enter password doesn't match": "Re-enter password doesn't match",
  'Change password': 'Change password',
  'Current password': 'Current password',
  'New password': 'New password',
  'Re-enter new password': 'Re-enter new password',
  'Education': 'Education',
  'Add new education': 'Add new education',
  'Specialization': 'Specialization',
  'University': 'University',
  'Degree': 'Degree',
  'Degree Type': 'Degree Type',
  'Started Date': 'Started Date',
  'Ended Date': 'Ended Date',
  'Verification request': 'Verification request',
  'Personal Information': 'Personal Information',
  'You should login or create new account to see your profile':
      'You should login or create new account to see your profile',
  'edit profile': 'edit profile',
  'Profile Progress': 'Profile Progress',
  'Personal information': 'Personal information',
  'Tutor request': 'Tutor request',
  'Profile description': 'Profile description',
  'Requests': 'Requests',
  'Recommendations': 'Recommendations',
  'Statistics': 'Statistics',
  'Payments': 'Payments',
  'Withdraw': 'Withdraw',
  'Become a Tutor': 'Become a Tutor',
  'Become a Student': 'Become a Student',
  'View profile': 'View profile',
  'Refer a friend': 'Refer a friend',
  '+ add  more Subject': '+ add  more Subject',
  '(MUST be related to the subject you are teaching)':
      '(MUST be related to the subject you are teaching)',
  'Pictures': 'Pictures',
  'Add another video URL': 'Add another video URL',
  'Insert your introduction video URL here':
      'Insert your introduction video URL here',
  'Youtube Video URL': 'Youtube Video URL',
  'Hourly rate': 'Hourly rate',
  'Subject title': 'Subject title',
  'Subject taught': 'Subject taught',
  'Insert your custom URL here': 'Insert your custom URL here',
  'Introduction Video': 'Introduction Video',
  "Master's degree and five years of experience teaching math to kids.":
      "Master's degree and five years of experience teaching math to kids.",
  'Introduction about yourself by other languages you can teach in':
      'Introduction about yourself by other languages you can teach in',
  'Introduce yourself': 'Introduce yourself',
  'Profile Bio': 'Profile Bio',
  'Copied': 'Copied',
  'Share your link': 'Share your link',
  'Share': 'Share',
  'You have earned': 'You have earned',
  'You should log In again': 'You should log In again',
  'Expected budget': 'Expected budget',
  'Details': 'Details',
  'Profile report': 'Profile report',
  'Views': 'Views',
  'Rate': 'Rate',
  'Score': 'Score',
  'Lessons And Students': 'Lessons And Students',
  'Total Students': 'Total Students',
  'All': 'All',
  'New': 'New',
  'Old': 'Old',
  'Total Lessons': 'Total Lessons',
  'Absences': 'Absences',
  'Canceled lessons': 'Canceled lessons',
  'Days': 'Days',
  'Profile score': 'Profile score',
  'Active student': 'Active student',
  'Last Month': 'Last Month',
  'This Month': 'This Month',
  'I’m looking for a French-language tutor for my daughter':
      'I’m looking for a French-language tutor for my daughter',
  'End': 'End',
  'Start': 'Start',
  'Verified': 'Verified',
  'Rating': 'Rating',
  'years': 'years',
  'Experience': 'Experience',
  'Students': 'Students',
  'About me': 'About me',
  'Teach': 'Teach',
  'Verified by admin': 'Verified by admin',
  'Review': 'Review',
  'REVIEW': 'REVIEW',
  'View all': 'View all',
  'Subjects to teach': 'Subjects to teach',
  'Book a session': 'Book a session',
  'Transaction': 'Transaction',
  'Your payments this month': 'Your payments this month',
  'Your earnings this month': 'Your earnings this month',
  'Earnings': 'Earnings',
  'Total Spent': 'Total Spent',
  'Balance': 'Balance',
  'You should login or create new account to see your chats':
      'You should login or create new account to see your chats',
  "You don't receive and messages yet": "You don't receive and messages yet",
  'Perfect space for anyone to learn or teach anything, anytime, anywhere, in any language.':
      'Perfect space for anyone to learn or teach anything, anytime, anywhere, in any language.',
  'Language': 'Language',
  'Allow Notification': 'Allow Notification',
  'Allow  the Notification Rings': 'Allow  the Notification Rings',
  'Date': 'Date',
  'Time': 'Time',
  'Type': 'Type',
  'Book private session': 'Book private session',
  'Select the subject of the session': 'Select the subject of the session',
  'Summary': 'Summary',
  'Schedule': 'Schedule',
  'Class Type': 'Class Type',
  'Cost': 'Cost',
  'Choose a plan': 'Choose a plan',
  'lessons': 'lessons',
  'you save': 'you save',
  'Continue': 'Continue',
  'No times for this day': 'No times for this day',
  'Users': 'Users',
  'Star': 'Star',
  'Speaks': 'Speaks',
  'Log Out': 'Log Out',
  'Are you sure to log out from this account?':
      'Are you sure to log out from this account?',
  'Thanks for purchasing!': 'Thanks for purchasing!',
  'Budget': 'Budget',
  'Offer details': 'Offer details',
  'Add offer': 'Add offer',
  'This Field is required': 'This Field is required',
  'Name is required': 'Name is required',
  'First name is required': 'First name is required',
  'Last name is required': 'Last name is required',
  'Email is required': 'Email is required',
  'Email invalid': 'Email invalid',
  'Password is required': 'Password is required',
  'Please make sure you are connected to the internet':
      'Please make sure you are connected to the internet',
  'Add new subject': 'Add new subject',
  'You can suggest new subject and it will be public after admin review':
      'You can suggest new subject and it will be public after admin review',
  'Subject Name': 'Subject Name',
  'Search Blogs': 'Search Blogs',
  'Search Community': 'Search Community',
  //end v1 02-10-2022
  'You haven\'t any tutor at your favourite':
      'You haven\'t any tutor at your favourite',
  'Phone is required': 'Phone is required',
  'Phone': 'Phone',
  'Time zone': 'Time zone',
  'Major': 'Major',
  'Answer': 'Answer',
  'Gender': 'Gender',
  'Male': 'Male',
  'Female': 'Female',
  'Result': 'Result',
  'Other': 'Other',
  'Add education': 'Add education',
  'Video URL': 'Video URL',
  '+ Add subject': '+ Add subject',
  '+ Add another subject': '+ Add another subject',
  'answer here': 'answer here',
  'Question': 'Question',
  'Speak': 'Speak',
  'Tutor native language': 'Tutor native language',
  'question here': 'question here',
  'Q&A': 'Q&A',
  'Add Q&A': 'Add Q&A',
  'Community (Q&A)': 'Community (Q&A)',
  'Contact reason': 'Contact reason',
  'Contact Us': 'Contact Us',
  'E.g., I’m looking for…': 'E.g., I’m looking for…',
  'E.g., Computer Science': 'E.g., Computer Science',
  'E.g., University of Cambridge': 'E.g., University of Cambridge',
  'Study years': 'Study years',
  'Hours per week': 'Hours per week',
  'Upload your certificate': 'Upload your certificate',
  'Filter': 'Filter',
  'Default': 'Default',
  'Recent': 'Recent',
  '+ Add certification': '+ Add certification',
  '+ Add another certification': '+ Add another certification',
  'Add Picture': 'Add Picture',
  'Insert your video URL here': 'Insert your video URL here',
  'Subject Pictures': 'Subject Pictures',
  'Subject Videos': 'Subject Videos',
  'Reviews': 'Reviews',
  'Position': 'Position',
  'Choose Country': 'Choose Country',
  'What’s Your Country/Region?': 'What’s Your Country/Region?',
  'This helps ensure that timetables display correctly in your local time.':
      'This helps ensure that timetables display correctly in your local time.',
  'Get Started': 'Get Started',
  'Level': 'Level',
  'Company': 'Company',
  'Description': 'Description',
  'You can suggest new category and it will be public after admin review':
      'You can suggest new category and it will be public after admin review',
  'Category Name': 'Category Name',
  'Add new category': 'Add new category',
  'Certification Hour': 'Certification Hour',
  'Country of origin': 'Country of origin',
  'Work date': 'Work date',
  'Add another experience': 'Add another experience',
  'Add work experience': 'Add work experience',
  'Add new work experience': 'Add new work experience',
  'Work experience': 'Work experience',
  'Sort by': 'Sort by',
  'Price from': 'Price from',
  'Max price': 'Max price',
  'You do not have any requests for tutors':
      'You do not have any requests for tutors',
  'Most rating': 'Most rating',
  'Best rating': 'Best rating',
  'End price': 'End price',
  'From price': 'From price',
  'Complete your profile': 'Complete your profile',
  'Date of birth': 'Date of birth',
  'Additional details is requird': 'Additional details is requird',
  'Category is requird': 'Category is requird',
  'blog image is requird': 'blog image is requird',
  'Verify': 'Verify',
  "Reset password": "Reset password",
  'Please enter your new password': 'Please enter your new password',
  'Confirmation password': 'Confirmation password',
  'Paypal': 'Paypal',
  'Wallet': 'Wallet',
  'Add Account': 'Add Account',
  'Cnacel': 'Cnacel',
  'Routing number': 'Routing number',
  'Account Holder': 'Account Holder',
  'Account number': 'Account number',
  'Account type': 'Account type',
  'Choose account': 'Choose account',
  'Amount': 'Amount',
  "Select Book time!": "Select Book time!",
  'Add new Classroom': 'Add new Classroom',
  "Are you sure to delete this classroom ?":
      "Are you sure to delete this classroom ?",
  "Alert!": "Alert!",
  "Classrooms": "Classrooms",
  "Add Classroom": "Add Classroom",
  'Classroom times': 'Classroom times',
  'Class room times not added yet!': 'Class room times not added yet!',
  "Start at : ": "Start at :",
  "End at : ": "End at :",
  'Max students': 'Max students',
  'Price': 'Price',
  "No classrooms": "No classrooms",
  "Classroom": "Classroom",
  "Subject name : ": "Subject name : ",
  "Price : ": "Price : ",
  "Books": "Books",
  'You already joined!': 'You already joined!',
  'Join group': 'Join group',
  'Available Classrooms': 'Available Classrooms',
  "Available Classes": "Available Classes",
  "Rescheduled Books": "Rescheduled Books",
  "No rescheduled books": "No rescheduled books",
  'Book details': 'Book details',
  "No Details available!": "No Details available!",
  "status : ": "status : ",
  "Old book": "Old book",
  "New book": "New book",
  'Approve': 'Approve',
  'Rejcet': 'Rejcet',
  "Are you sure to reject the new book?":
      "Are you sure to reject the new book?",
  "Book Actions": "Book Actions",
  'Rescheduled': 'Rescheduled',
  'Cancel book': 'Cancel book',
  "Are you sure to cancel this book ?": "Are you sure to cancel this book ?",

  "Are you sure to delete this time ?": "Are you sure to delete this time ?",
  'Close': 'Close',
  "Suggested Books": "Suggested Books",
  "No sugget books": "No sugget books",
  'Suggest book': 'Suggest book',
  "No Suggest details!": "No Suggest details!",
  "Suggest Book": "Suggest Book",
  "Are you sure to delete this Suggest book?":
      "Are you sure to delete this Suggest book?",
  "Canceled Books": "Canceled Books",
  "No canceled books": "No canceled books",
  "No community posts.": "No community posts.",
  "No blogs.": "No blogs.",
  "Are you sure to delete this blog ?": "Are you sure to delete this blog ?",
  "Are you sure to delete this post?": "Are you sure to delete this post?",
  "Show Offers": "Show Offers",
  "Offers": "Offers",
  "No post ;Acceptdetails!":"No post details!" , 
  "Accept"  :"Accept" , 
   "No offers yet!": "No offers yet!", 
  "Reject":"Reject" , 
   "Are you sure to reject this offer?": "Are you sure to reject this offer?" , 


};
